location = /wp-config.php { deny all; }
location = /xmlrpc.php { deny all; }
location ~* /\.git { deny all; }
location ~* /\.env { deny all; }
location ~* /readme\.html { deny all; }
location ~* /license\.txt { deny all; }
location ~* /wp-content/debug\.log { deny all; }
location ~* /(?:uploads|files)/.*\.php$ { deny all; }
